create table if not exists public.portfolio_projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  project_url text not null unique,
  image_url text not null,
  technologies text[] not null default '{}',
  github_repo text,
  source text not null default 'manual' check (source in ('manual', 'github')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists portfolio_projects_created_at_idx
  on public.portfolio_projects (created_at desc);

alter table public.portfolio_projects enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'portfolio_projects'
      and policyname = 'Public read portfolio projects'
  ) then
    create policy "Public read portfolio projects"
      on public.portfolio_projects
      for select
      using (true);
  end if;
end
$$;

insert into public.portfolio_projects (
  title,
  description,
  project_url,
  image_url,
  technologies,
  github_repo,
  source
)
values
  (
    'Diario Contabil',
    'Sistema de gestao de assinaturas MEI com checkout transparente e automacao de cobrancas.',
    'https://mei-landing.vercel.app/',
    '/diario-contabil.png',
    '{Next.js,Tailwind CSS,TypeScript,Node.js,Git}',
    null,
    'manual'
  ),
  (
    'API Barber',
    'Sistema de gestao de clientes com planos, renovacao e status dinamico para barbearia.',
    'https://github.com/LucasSantos96/api_barber',
    '/system-barber.png',
    '{Next.js,Tailwind CSS,TypeScript,Prisma,Node.js,MySQL,Git}',
    'https://github.com/LucasSantos96/api_barber',
    'manual'
  ),
  (
    'Edu ai',
    'Geracao automatizada de planos de estudo com n8n, IA e dashboard de acompanhamento.',
    'https://saas-study-21vg.vercel.app/',
    '/eduai.png',
    '{React,Node.js,SQLite,Git,n8n}',
    null,
    'manual'
  ),
  (
    'Stefani Fotografia',
    'Landing page responsiva para fotografa profissional com foco em conversao e portfolio visual.',
    'https://lp-stefani.vercel.app/',
    '/stefani.png',
    '{Next.js,Tailwind CSS,TypeScript,Git}',
    null,
    'manual'
  ),
  (
    'BlogNode',
    'Aplicacao fullstack com autenticacao, CRUD de posts e organizacao por categorias.',
    'https://blognode-mntu.onrender.com/',
    '/blognode.png',
    '{Node.js,Express,MongoDB,JavaScript,Bootstrap,Git}',
    null,
    'manual'
  ),
  (
    'Shanty',
    'Projeto front-end de estúdio de yoga com base em prototipo Figma e foco em UX responsiva.',
    'https://lpyoga.vercel.app/',
    '/shanty.png',
    '{Next.js,Tailwind CSS,JavaScript,Git}',
    null,
    'manual'
  ),
  (
    'Um sol pra cada um',
    'Projeto Next.js baseado em Figma para praticar hierarquia visual e componentizacao.',
    'https://sunglassesproject-git-main-lucassantos96s-projects.vercel.app',
    '/projetoOculos.png',
    '{Next.js,Tailwind CSS,JavaScript,Git}',
    null,
    'manual'
  ),
  (
    'Ticket Generator',
    'Desafio Frontend Mentor com foco em formularios e experiencia de criacao de tickets.',
    'https://ticket-generator-kwl1-git-main-lucassantos96s-projects.vercel.app',
    '/projectTicket.png',
    '{Next.js,Tailwind CSS,TypeScript,Git}',
    null,
    'manual'
  ),
  (
    'Boa forma',
    'Site com calculo de IMC e conteudos de saude usando HTML, CSS e JavaScript.',
    'https://lucassantos96.github.io/boa-forma/',
    '/boaForma.png',
    '{HTML,CSS,JavaScript,Git}',
    null,
    'manual'
  ),
  (
    'Links Seu Beca',
    'Pagina de links uteis para barbearia com acesso rapido aos canais da marca.',
    'https://lucassantos96.github.io/linksseubeca/',
    '/seuBeca.png',
    '{HTML,CSS,JavaScript,Git}',
    null,
    'manual'
  )
on conflict (project_url) do update
set
  title = excluded.title,
  description = excluded.description,
  image_url = excluded.image_url,
  technologies = excluded.technologies,
  github_repo = excluded.github_repo,
  source = excluded.source,
  updated_at = now();
